version: '3.9'

services:
  frontend-app:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/frontend-app
      - /frontend-app/node_modules
    restart: always
    command: 'pnpm run dev'