version: '3.9'

services:
  backend:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    command: pnpm start:dev
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - data:/var/lib/postgresql/data 
  
volumes:
  data: